version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/mysql-dump:/docker-entrypoint-initdb.d
      - ./data/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: analyser
    ports:
      - 3306:3306

  analyser:
    image: khalifarsm/analyser
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    environment:
      DW_HOME: /data/responses
    depends_on:
      - db

  plantuml:
    image: khalifarsm/plantuml-server
    restart: always
    ports:
      - 8082:8080