version: '3.1'

services:

  analyser:
    image: khalifarsm/analyser
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    environment:
      DW_HOME: /data/responses
    depends_on:
      - db

  plantuml:
    image: khalifarsm/plantuml-server
    restart: always
    ports:
      - 8082:8080